# Generated by Django 4.2 on 2024-10-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='allergy_bee',
            field=models.BooleanField(default=False, verbose_name='Аллергия на продукты пчеловодства'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergy_cereal',
            field=models.BooleanField(default=False, verbose_name='Аллергия на зерновые'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergy_fish',
            field=models.BooleanField(default=False, verbose_name='Аллергия на рыбу и морепродукты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergy_meat',
            field=models.BooleanField(default=False, verbose_name='Аллергия на мясо'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergy_milk',
            field=models.BooleanField(default=False, verbose_name='Аллергия на молочные продукты'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='allergy_nuts',
            field=models.BooleanField(default=False, verbose_name='Аллергия на орехи и бобовые'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='breakfast',
            field=models.BooleanField(default=True, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dessert',
            field=models.BooleanField(default=True, verbose_name='Десерт'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dinner',
            field=models.BooleanField(default=True, verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lunch',
            field=models.BooleanField(default=True, verbose_name='Обед'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recommend',
            field=models.BooleanField(default=True, verbose_name='Рекомендовать пользователям'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='foodtype',
            field=models.CharField(choices=[('classic', 'Классическое'), ('low', 'Низкоуглеводное'), ('veg', 'Вегетарианское'), ('keto', 'Кето')], max_length=50, verbose_name='Тип диеты'),
        ),
    ]
